base_config: configs/tts/transformer_tts.yaml

# data
dict_file: dict
data_dir: 'data/ljspeech'
raw_data_dir: 'data/raw/LJSpeech-1.1'

# model
arch: '2 7 4 3 5 6 3 4' # sep5 sep25 sep13 sep9 sep17 sep21 sep9 sep13
hidden_size: 256
filter_size: 1024
enc_layers: 4
dec_layers: 4
ffn_kernel_size: 9
use_energy_embed: False
predictor_layer_type: 'sepconv'
activation: 'relu'
dropout: 0.2
activation_dropout: 0.2
max_tokens: 28000
val_check_interval: 1000
max_updates: 100000
predictor_sg: true

# duration
predictor_hidden: 256
dur_predictor_kernel: 3
use_gt_dur: false
sep_dur_loss: true
dur_predictor_layer: 2

# pitch and energy
use_pitch_embed: true
use_uv: true
use_energy_embed: False
pitch_loss: 'l1'
pitch_predictor_layer: 5
energy_predictor_layer: 5

# loss
lambda_dur: 1.0
lambda_pitch: 1.0
lambda_uv: 1.0
lambda_energy: 1.0
mel_loss: l1

# train and eval
pretrain_fs_ckpt: ''
warmup_updates: 2000
max_tokens: 28000
max_sentences: -1
max_eval_sentences: 1
max_updates: 200000
gen_dir_name: ''